analysis specs:
  sacc_data: "sacc_data"
  ell_min: 2
  ell_max: 1500
  n_ell: 1501

tracers:
  lens_spec:
    tracer_name: "lens_spec"
    n_bins: 10
    z_start: 0.333
    z_stop: 0.667
    z_err: 0.003
    z0: 0.318696

  lens:
    tracer_name: "lens"
    n_bins: 5
    z_start: 0.
    z_stop: 1.
    z_err: 0.03
    z0: 0.354107
  
  src:
    tracer_name: "source"
    n_bins: 5
    z_start: 0.0
    z_stop: 1
    z_err: 0.03
    z0: 0.354107

cosmo parameters:
  Omega_c: 0.27
  Omega_b: 0.045
  h: 0.67
  A_s: 2.1e-9
  n_s: 0.96
  Neff: 3.044
  m_nu: 0.12
  mass_split: 'normal'
  extra_parameters:
    camb:
      halofit_version: "mead2020"